DROP TABLE IF EXISTS TB_DISPOSABLE_SALT_INFO;
CREATE TABLE TB_DISPOSABLE_SALT_INFO (
	 ID 						BIGINT AUTO_INCREMENT
	,USER_ID 					BIGINT
	,SUBJECT  			        VARCHAR(64) NOT NULL
	,SALT  			            VARCHAR(512) NOT NULL
	,DELETES					BOOLEAN   NOT NULL DEFAULT FALSE
  	,CREATED_AT					TIMESTAMP DEFAULT now()
  	,UPDATED_AT					TIMESTAMP DEFAULT now()
	,PRIMARY KEY (ID)
	,UNIQUE(USER_ID,SUBJECT)
);